import './globals.css'
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";
import SignInButton from './components/SigninButton';
import { PrismaClient } from '.prisma/client';
import { Montserrat } from 'next/font/google'
import SignOutButton from './components/SignoutButton'
import Nav from './components/Nav';

const montserrat = Montserrat({
  weight: ['100', '200', '300', '400'],
  subsets: ['latin'],
  variable: '--font-mont'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const prisma = new PrismaClient()

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const authorizedEmail = await prisma.authorizedEmail.findUnique({
    where: {
      id: 1
    },
    select: {
      email: true
    }
  })
  const session = await getServerSession(authOptions)
  return (
    <html lang="en" className={`${montserrat.variable} p-10`}>
      {!session?.user && (
        <body className="flex justify-center text-xl text-mytheme font-bold hover:font-black">
          <SignInButton />
        </body>
      )}
      {session?.user && session?.user?.email !== authorizedEmail?.email && (
        <body className='fex text-xl font-bold'>
          <p>Sorry this email is not authorized</p>
          <SignOutButton />
        </body>
      )}
      {session?.user && session?.user?.email === authorizedEmail?.email && (
        <body>
          <Nav />
          {children}
          </body>
      )}
    </html>
  )
}
