import './globals.css'
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";
import SignInButton from './components/SigninButton';
import { PrismaClient } from '.prisma/client';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const prisma = new PrismaClient()

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const authorizedEmail = await prisma.authorizedEmail.findUnique({
    where: {
      id: 1
    },
    select: {
      email: true
    }
  })
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      {!session?.user && (
        <body>
          <SignInButton />
        </body>
      )}
      {session?.user && session?.user?.email !== authorizedEmail?.email && (
        <body>
          <h1>Sorry this email is not authorized</h1>
        </body>
      )}
      {session?.user && session?.user?.email === authorizedEmail?.email && (
        <body>{children}</body>
      )}
    </html>
  )
}
